# -*- coding: utf-8 -*-
#
#   Dao-Ke-Dao: Universal Message Module
#
#                                Written in 2019 by Moky <albert.moky@gmail.com>
#
# ==============================================================================
# MIT License
#
# Copyright (c) 2019 Albert Moky
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ==============================================================================

from abc import ABC, abstractmethod
from typing import Optional, Any, List
from typing import Iterable

from mkm.types import StrMap, MutableStrMap
from mkm.format import TransportableData

from .secure import SecureMessage
from .envelope import shared_message_extensions


class ReliableMessage(SecureMessage, ABC):
    """Interface for signed reliable messages (third/final stage).

    Extends `SecureMessage` with a digital signature generated by the sender's
    private key, providing both confidentiality (from encryption) and authenticity/
    integrity (from signing). This is the final stage of message transformation
    for secure transmission.

    Serialized format (Map/JSON):
    ```json
    {
      // Envelope metadata (unchanged from previous stages)
      "sender"    : "moki@xxx",  // Sender's unique ID
      "receiver"  : "hulk@yyy",  // Receiver's unique ID
      "time"      : 123.45,      // Message timestamp (Unix timestamp in seconds)

      // Encrypted content data and keys (from SecureMessage)
      "data"      : "...",       // base64_encode( symmetric_encrypt(content))
      "keys"      : {
        "{ReceiverID}" : "...",  // base64_encode(asymmetric_encrypt(pwd))
        "digest"       : "..."   // hash(pwd.data)
      },
      // Digital signature (new for ReliableMessage)
      "signature" : "..."        // Base64-encoded signature (signed with sender's private key)
    }
    ```
    """

    @property
    @abstractmethod
    def signature(self) -> TransportableData:
        """Digital signature of the encrypted `data` field.

        Generated by signing the `data` (encrypted content) with the sender's
        private key (asymmetric signing). This signature verifies the message's
        authenticity (sender is who they claim to be) and integrity (message hasn't
        been tampered with). Wrapped in `TransportableData` for standardized
        encoding/transmission. Cannot be None (core security feature of reliable
        messages).
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.signature getter'
        )

    #
    #   Conveniences
    #

    @classmethod
    def convert(cls, array: Iterable):  # -> List[ReliableMessage]:
        """Convert an array of raw objects into `ReliableMessage` instances.

        :param array: list of raw message data (map/JSON)
        :return: list of parsed `ReliableMessage` instances (invalid items are skipped)
        """
        messages = []
        for item in array:
            msg = cls.parse(msg=item)
            if msg is None:
                # message error
                continue
            messages.append(msg)
        return messages

    @classmethod
    def revert(cls, messages: Iterable) -> List[MutableStrMap]:
        """Convert `ReliableMessage` instances back to raw map objects.

        :param messages: list of `ReliableMessage` instances
        :return: list of serialized map (JSON) objects
        """
        array = []
        for msg in messages:
            assert isinstance(msg, ReliableMessage), f'message error: {msg}'
            array.append(msg.to_map())
        return array

    #
    #   Factory methods
    #

    @classmethod
    def from_secure_message(cls, s_msg: SecureMessage, signature: bytes):
        """Create a `ReliableMessage` from a secure message, adding 'signature'.

        Signs the encrypted content data with the sender's private key, forming
        the digital signature for authenticity and integrity verification.

        :param s_msg:     is the encrypted secure message.
        :param signature: is the signature of the encrypted content data.
        :return: a new `ReliableMessage` instance.
        """
        helper = reliable_helper()
        return helper.create_reliable_message(s_msg=s_msg, signature=signature)

    @classmethod
    def parse(cls, msg: Any):  # -> Optional[ReliableMessage]:
        """Parse a raw object into a `ReliableMessage` instance.

        :param msg: raw message data (map, JSON string, etc.)
        :return: parsed `ReliableMessage` instance, or None if parsing fails
        """
        helper = reliable_helper()
        return helper.parse_reliable_message(msg=msg)

    @classmethod
    def get_factory(cls):  # -> Optional[ReliableMessageFactory]:
        """Get the reliable message factory.

        :return: registered `ReliableMessageFactory`, or None if not registered
        """
        helper = reliable_helper()
        return helper.get_reliable_message_factory()

    @classmethod
    def set_factory(cls, factory):
        """Register the reliable message factory.

        :param factory: factory to be registered
        """
        helper = reliable_helper()
        return helper.set_reliable_message_factory(factory=factory)


class ReliableMessageFactory(ABC):
    """Factory interface for parsing `ReliableMessage` instances from serialized data.

    Provides a method to reconstruct reliable messages from their serialized Map/JSON
    representation, with validation of both encrypted data and digital signature.
    """

    @abstractmethod
    def create_reliable_message(self, s_msg: SecureMessage, signature: bytes):
        """Create a reliable message from secure message, adding 'signature'.

        Signs the encrypted content data with the sender's private key, forming
        the digital signature for authenticity and integrity verification.

        :param s_msg:     is the encrypted message.
        :param signature: is the signature of the encrypted content data.
        :return: a `ReliableMessage` instance.
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.create_reliable_message()'
        )

    @abstractmethod
    def parse_reliable_message(self, msg: StrMap) -> Optional[ReliableMessage]:
        """Parses a serialized Map into a `ReliableMessage` instance.

        Validates the structure (required fields: data, keys, signature) and
        converts raw values (e.g., Base64 string -> TransportableData for
        signature) to proper types.

        :param msg: serialized reliable message data (matches format in `ReliableMessage`)
        :return: a `ReliableMessage` instance if parsing succeeds, None otherwise
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.parse_reliable_message()'
        )


# -----------------------------------------------------------------------------
#  Message Extensions
# -----------------------------------------------------------------------------


class ReliableMessageHelper(ABC):
    """Helper interface for reliable message management.

    Manages reliable message factories and provides core functionality for:
    - Creating reliable messages (secure message + signature)
    - Parsing raw reliable message data into strongly-typed `ReliableMessage` instances

    ReliableMessage represents a signed secure message (SecureMessage after signing)
    that ensures message integrity and authenticity (non-repudiation).
    """

    @abstractmethod
    def set_reliable_message_factory(self, factory: ReliableMessageFactory):
        """Set the reliable message factory.

        :param factory: factory to be registered
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.set_reliable_message_factory()'
        )

    @abstractmethod
    def get_reliable_message_factory(self) -> Optional[ReliableMessageFactory]:
        """Get the reliable message factory.

        :return: registered `ReliableMessageFactory`, or None if not registered
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.get_reliable_message_factory()'
        )

    @abstractmethod
    def create_reliable_message(self, s_msg: SecureMessage, signature: bytes):
        """Create a reliable message from secure message, adding 'signature'.

        Signs the encrypted content data with the sender's private key, forming
        the digital signature for authenticity and integrity verification.

        :param s_msg:     is the encrypted secure message.
        :param signature: is the signature of the encrypted content data.
        :return: a new `ReliableMessage` instance.
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.create_reliable_message()'
        )

    @abstractmethod
    def parse_reliable_message(self, msg: Any) -> Optional[ReliableMessage]:
        """Parses raw reliable message data into a strongly-typed `ReliableMessage` instance.

        Converts arbitrary raw reliable message data (e.g., map, JSON string) into a
        valid ReliableMessage object for signature verification and decryption.

        :param msg: raw reliable message data to parse
        :return: parsed `ReliableMessage` instance (None if parsing fails)
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.parse_reliable_message()'
        )


class ReliableMessageExtension:

    @property
    def reliable_helper(self) -> Optional[ReliableMessageHelper]:
        """ Get reliable message helper """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.reliable_helper getter'
        )

    @reliable_helper.setter
    def reliable_helper(self, helper: ReliableMessageHelper):
        """ Set reliable message helper """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.reliable_helper setter'
        )


shared_message_extensions.reliable_helper: Optional[ReliableMessageHelper] = None


def message_extensions() -> ReliableMessageExtension:
    return shared_message_extensions


def reliable_helper() -> ReliableMessageHelper:
    ext = message_extensions()
    return ext.reliable_helper
