# -*- coding: utf-8 -*-
#
#   Dao-Ke-Dao: Universal Message Module
#
#                                Written in 2019 by Moky <albert.moky@gmail.com>
#
# ==============================================================================
# MIT License
#
# Copyright (c) 2019 Albert Moky
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ==============================================================================

from abc import ABC, abstractmethod
from typing import Optional, Any, Dict

from mkm.types import StrMap
from mkm.format import TransportableData
from mkm.protocol import ID

from ..crypto import EncryptedBundle

from .message import Message
from .instant import InstantMessage
from .envelope import shared_message_extensions


class SecureMessage(Message, ABC):
    """Interface for encrypted secure messages (second stage).

    Represents an `InstantMessage` that has been encrypted with a symmetric key,
    providing confidentiality for the message content. The original plaintext
    content is replaced with encrypted data and encrypted keys for decryption.

    Serialized format (Map/JSON):
    ```json
    {
      // Envelope metadata (unchanged from InstantMessage)
      "sender"    : "moki@xxx",  // Sender's unique ID
      "receiver"  : "hulk@yyy",  // Receiver's unique ID
      "time"      : 123.45,      // Message timestamp (Unix timestamp in seconds)

      // Encrypted content data and keys
      "data"      : "...",       // base64_encode( symmetric_encrypt(content))
      "keys"      : {
        "{ReceiverID}" : "...",  // base64_encode(asymmetric_encrypt(pwd))
        "digest"       : "..."   // hash(pwd.data)
      }
    }
    ```
    """

    @property
    @abstractmethod
    def data(self) -> TransportableData:
        """Encrypted message content (Base64-encoded).

        Generated by encrypting the `InstantMessage.content` with a symmetric key
        (e.g., AES). Wrapped in `TransportableData` for standardized
        encoding/transmission. Cannot be None (core payload of the secure message).
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.data getter'
        )

    @property
    @abstractmethod
    def encrypted_keys(self) -> Optional[StrMap]:  # str => str
        """Map of encrypted symmetric keys (recipient ID -> encrypted key string).

        Each entry contains a symmetric key encrypted with the recipient's public
        key (asymmetric encryption), ensuring only the intended recipient can
        decrypt it. The "digest" entry contains a hash of the raw symmetric key
        for verification.

        :return: map of encrypted keys, or None if no keys are present (uncommon)
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.encrypted_keys getter'
        )

    #
    #   Factory methods
    #

    @classmethod
    def from_instant_message(cls, i_msg: InstantMessage, data: bytes, bundles: Dict[ID, EncryptedBundle] = None):
        """Create a `SecureMessage` from an instant message, adding 'data' and 'keys'.

        Encrypts the plaintext content with a symmetric key, then encrypts the key
        for each receiver terminal, forming the encrypted data and key bundles.

        :param i_msg:   is the plain instant message.
        :param data:    is the encrypted data of the content.
        :param bundles: is the encrypted key bundles for the receiver terminals.
        :return: a new `SecureMessage` instance.
        """
        helper = secure_helper()
        return helper.create_secure_message(i_msg=i_msg, data=data, bundles=bundles)

    @classmethod
    def parse(cls, msg: Any):  # -> Optional[SecureMessage]:
        """Parse a raw object into a `SecureMessage` instance.

        :param msg: raw message data (map, JSON string, etc.)
        :return: parsed `SecureMessage` instance, or None if parsing fails
        """
        helper = secure_helper()
        return helper.parse_secure_message(msg=msg)

    @classmethod
    def get_factory(cls):  # -> Optional[SecureMessageFactory]:
        """Get the secure message factory.

        :return: registered `SecureMessageFactory`, or None if not registered
        """
        helper = secure_helper()
        return helper.get_secure_message_factory()

    @classmethod
    def set_factory(cls, factory):
        """Register the secure message factory.

        :param factory: factory to be registered
        """
        helper = secure_helper()
        helper.set_secure_message_factory(factory=factory)


class SecureMessageFactory(ABC):
    """Factory interface for parsing `SecureMessage` instances from serialized data.

    Provides a method to reconstruct secure messages from their serialized Map/JSON
    representation, with proper validation of encrypted data and keys.
    """

    @abstractmethod
    def create_secure_message(self, i_msg: InstantMessage, data: bytes, bundles: Optional[Dict[ID, EncryptedBundle]]):
        """Create a secure message from instant message, adding 'data' and 'keys'.

        Encrypts the plaintext content with a symmetric key, then encrypts the key
        for each receiver terminal, forming the encrypted data and key bundles.

        :param i_msg:   is the plain message (with envelope and content).
        :param data:    is the encrypted data of the content.
        :param bundles: is the encrypted key bundles (terminal -> encrypted key data).
        :return: a `SecureMessage` instance.
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.create_secure_message()'
        )

    @abstractmethod
    def parse_secure_message(self, msg: StrMap) -> Optional[SecureMessage]:
        """Parses a serialized Map into a `SecureMessage` instance.

        Validates the structure (required fields: sender, receiver, data) and
        converts raw values (e.g., Base64 string -> TransportableData) to proper
        types.

        :param msg: serialized secure message data (matches format in `SecureMessage`)
        :return: a `SecureMessage` instance if parsing succeeds, None otherwise
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.parse_secure_message()'
        )


# -----------------------------------------------------------------------------
#  Message Extensions
# -----------------------------------------------------------------------------


class SecureMessageHelper(ABC):
    """Helper interface for secure message management.

    Manages secure message factories and provides core functionality for:
    - Creating secure messages (instant message + encrypted data + key bundles)
    - Parsing raw secure message data into strongly-typed `SecureMessage` instances

    SecureMessage represents an encrypted message (InstantMessage after encryption)
    that protects the content from unauthorized access.
    """

    @abstractmethod
    def set_secure_message_factory(self, factory: SecureMessageFactory):
        """Set the secure message factory.

        :param factory: factory to be registered
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.set_secure_message_factory()'
        )

    @abstractmethod
    def get_secure_message_factory(self) -> Optional[SecureMessageFactory]:
        """Get the secure message factory.

        :return: registered `SecureMessageFactory`, or None if not registered
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.get_secure_message_factory()'
        )

    @abstractmethod
    def create_secure_message(self, i_msg: InstantMessage, data: bytes, bundles: Optional[Dict[ID, EncryptedBundle]]):
        """Create a secure message from instant message, adding 'data' and 'keys'.

        Encrypts the plaintext content with a symmetric key, then encrypts the key
        for each receiver terminal, forming the encrypted data and key bundles.

        :param i_msg:   is the plain instant message.
        :param data:    is the encrypted data of the content.
        :param bundles: is the encrypted key bundles for the receiver terminals.
        :return: a new `SecureMessage` instance.
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.create_secure_message()'
        )

    @abstractmethod
    def parse_secure_message(self, msg: Any) -> Optional[SecureMessage]:
        """Parses raw secure message data into a strongly-typed `SecureMessage` instance.

        Converts arbitrary raw secure message data (e.g., map, JSON string) into a
        valid SecureMessage object for decryption and processing.

        :param msg: raw secure message data to parse
        :return: parsed `SecureMessage` instance (None if parsing fails)
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.parse_secure_message()'
        )


class SecureMessageExtension:

    @property
    def secure_helper(self) -> Optional[SecureMessageHelper]:
        """ Get secure message helper """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.secure_helper getter'
        )

    @secure_helper.setter
    def secure_helper(self, helper: SecureMessageHelper):
        """ Set secure message helper """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.secure_helper setter'
        )


shared_message_extensions.secure_helper: Optional[SecureMessageHelper] = None


def message_extensions() -> SecureMessageExtension:
    return shared_message_extensions


def secure_helper():
    ext = message_extensions()
    return ext.secure_helper
